export const architectPackages = [
  {
    id: 1,
    name: "Paket Desain Esensial",
    description: "Cocok untuk desain standar yang efisien dan minimalis.",
    pricePerSquareMeter: 50000,
    features: [
      { feature: "Denah Tata Ruang (2D)", included: true },
      { feature: "Desain Eksterior (Tampak Depan)", included: true },
      { feature: "Site Plan (Denah Situasi Bangunan)", included: true },
      { feature: "Desain 3D Visual Eksterior", included: false },
      { feature: "Gambar Teknis (DED)", included: false },
      { feature: "Rencana Anggaran Biaya (RAB)", included: false },
      { feature: "Revisi Desain", included: "1 kali" },
      { feature: "Animasi 3D", included: false },
      { feature: "Desain Interior", included: false },
      { feature: "Konsultasi Desain", included: false },
    ],
  },
  {
    id: 2,
    name: "Paket Desain Lanjutan",
    description: "Pilihan ideal untuk desain yang lebih mendetail.",
    pricePerSquareMeter: 75000,
    features: [
      { feature: "Denah Tata Ruang (2D)", included: true },
      { feature: "Desain Eksterior (Tampak Depan)", included: true },
      { feature: "Site Plan (Denah Situasi Bangunan)", included: true },
      { feature: "Desain 3D Visual Eksterior", included: true },
      { feature: "Gambar Teknis (DED)", included: true },
      { feature: "Rencana Anggaran Biaya (RAB)", included: true },
      { feature: "Revisi Desain", included: "3 kali" },
      { feature: "Animasi 3D", included: false },
      { feature: "Desain Interior", included: false },
      { feature: "Konsultasi Desain", included: true },
    ],
  },
  {
    id: 3,
    name: "Paket Premium Lengkap",
    description:
      "Solusi lengkap untuk kebutuhan desain arsitek yang menyeluruh.",
    pricePerSquareMeter: 100000,
    features: [
      { feature: "Denah Tata Ruang (2D)", included: true },
      { feature: "Desain Eksterior (Tampak Depan)", included: true },
      { feature: "Site Plan (Denah Situasi Bangunan)", included: true },
      { feature: "Desain 3D Visual Eksterior", included: true },
      { feature: "Gambar Teknis (DED)", included: true },
      { feature: "Rencana Anggaran Biaya (RAB)", included: true },
      { feature: "Revisi Desain", included: "Unlimited" },
      { feature: "Animasi 3D", included: true },
      { feature: "Desain Interior", included: true },
      { feature: "Konsultasi Desain", included: true },
    ],
  },
];
